### ISSUE TITLE
Một số bảng và trường trong DB hiện tại đang để tiếng Việt

### ISSUE THREAD

**Issue by chungth** [hungtt57/khoaluan#5]
Ví dụ: https://github.com/hungtt57/khoaluan/blob/master/database/migrations/2016_01_28_174223_create_products_table.php

Không biết có lý do đặc biệt nào khi để tên tiếng Việt hay không ? 
Theo a hiểu thì nên để tên tiếng Anh để có thể làm việc với Developer dùng nhiều ngôn ngữ 
khác nhau.

**Comment by hungtt57** [comment]
Hiện tại em dùng tiếng anh rồi ạ :) :) hồi đó chưa có kinh nghiệm
